options:
  enable-advanced-routing:
    type: boolean
    default: False
    description: |
      Whether to use the custom routing configuration provided by the charm.
  advanced-routing-config:
    type: string
    default: "[]"
    description: |
      A json array consisting of objects, e.g.
      [ {
          "type": "route",
          "net": "192.170.1.0/24",
          "device": "eth5"
      }, { ... } ]
      @ see example_config.yaml for more examples
